# Netlify Configuration for H&S Platform
# This deploys the Next.js modern-platform (production-ready)

[build]
  base = "."
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Next.js auto-detection - Netlify will automatically detect and configure Next.js
# No explicit plugin needed for Next.js 15+

# Next.js ISR (Incremental Static Regeneration) support
# Functions configuration removed - Netlify auto-detection handles this

# Cache static assets (Next.js specific paths)
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.airtable.com https://hook.us1.make.com;"
