# Netlify Configuration for H&S Platform
# This deploys the Next.js modern-platform (production-ready)

[build]
  # Base directory is the repo root (modern-platform-frontend is already the frontend)
  publish = ".next"
  command = "npm install --prefer-offline=false && npm run build"

[build.environment]
  NODE_VERSION = "20"

  # ⚠️  IMPORTANT: All sensitive environment variables MUST be set in Netlify UI
  # Navigate to: Site Settings > Environment Variables
  #
  # Required environment variables to set in Netlify UI:
  # - NEXT_PUBLIC_BACKEND_URL (e.g., https://hs-andru-test.onrender.com)
  # - NEXT_PUBLIC_SUPABASE_URL (e.g., https://molcqjsqtjbfclasynpg.supabase.co)
  # - NEXT_PUBLIC_SUPABASE_ANON_KEY (Supabase anonymous/public key)
  #
  # DO NOT commit API keys, tokens, or secrets to this file!

# Next.js auto-detection - Netlify will automatically detect and configure Next.js
# No explicit plugin needed for Next.js 15+

# Next.js ISR (Incremental Static Regeneration) support
# Functions configuration removed - Netlify auto-detection handles this

# Cache static assets (Next.js specific paths)
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Security headers (Enhanced - Oct 16, 2025)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    # Production CSP - tightened for security (unsafe-eval removed)
    # Next.js 15+ uses runtime compilation that doesn't require unsafe-eval in production
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https: blob:; connect-src 'self' https://molcqjsqtjbfclasynpg.supabase.co https://hs-andru-test.onrender.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
