// Business Case Builder - TypeScript Type Definitions
// Based on one-page business case template structure
// Auto-populates from ICP Analysis and Cost Calculator results

// =============================================================================
// AUTO-POPULATION SOURCE TRACKING
// =============================================================================

/**
 * Tracks the source of each data field for transparency and validation
 */
export enum AutoPopulationSource {
  ICP = 'ICP',                          // From ICP Analysis tool
  COST_CALCULATOR = 'COST_CALCULATOR',  // From Cost Calculator results
  USER_PROVIDED = 'USER_PROVIDED',      // Manually entered by user
  AI_GENERATED = 'AI_GENERATED',        // Generated by AI from context
  HYBRID = 'HYBRID'                     // Combination of sources
}

/**
 * Field metadata for tracking auto-population
 */
export interface FieldMetadata {
  source: AutoPopulationSource;
  lastUpdated: Date;
  isEditable: boolean;
  confidence?: number; // 0-1 for AI-generated fields
}

// =============================================================================
// SECTION 1: HEADER
// =============================================================================

export interface BusinessCaseHeader {
  // Executive-level headline (AI-generated from template context)
  priorityHeadline: string;

  // Champion information (user-provided)
  championName: string;
  championTitle: string;

  // Partnership information (user-provided)
  partnerName: string;
  partnerCompany: string;

  // Metadata
  generatedDate: Date;
  companyName: string; // From ICP or user-provided
}

// =============================================================================
// SECTION 2: EXECUTIVE SUMMARY
// =============================================================================

export interface ExecutiveSummary {
  // Core narrative components
  businessChange: string;           // The specific change/challenge (ICP or user-provided)
  recommendedSolution: string;      // Your solution description (user-provided)
  implementationTimeline: string;   // Timeline for deployment (user-provided)
  currentCostPain: string;          // What gets eliminated (Cost Calculator)
  strategicOutcome: string;         // What gets enabled (user-provided)
  executiveGoal: string;            // Executive's committed goal (user-provided or ICP)

  // Full narrative (AI-generated from components)
  fullSummary: string;
}

// =============================================================================
// SECTION 3: BUSINESS CHALLENGE
// =============================================================================

export interface BusinessChallenge {
  // Current Reality
  currentRealityDescription: string; // Champion's problem description (user-provided)

  // Cost of Status Quo - structured fields
  frequency: string;                 // "Every [day/week/month]" (user-provided)
  affectedCount: number;             // Number of people/transactions (Cost Calculator or ICP)
  affectedStakeholders: string;      // Type of stakeholders (ICP)
  specificProblem: string;           // The problem they experience (user-provided)
  dollarCost: number;                // Quantified cost (Cost Calculator)

  // Consequence without action
  consequenceTimeline: string;       // "Without action by [date]" (user-provided)
  consequence: string;               // What happens (champion's language) (user-provided)

  // Full narrative (AI-generated from components)
  fullCostOfStatusQuo: string;
}

// =============================================================================
// SECTION 4: APPROACH & DIFFERENTIATION
// =============================================================================

export interface KeyCapability {
  title: string;                     // Capability name (user-provided)
  problemSolved: string;             // Specific problem it solves (user-provided)
  businessOutcome: string;           // Business outcome delivered (user-provided)
}

export interface ThreePhaseFramework {
  phase1: string;                    // Immediate wins (user-provided)
  phase2: string;                    // Committee concerns addressed (user-provided)
  phase3: string;                    // Strategic outcomes (user-provided)
}

export interface ApproachDifferentiation {
  // Discovery context
  discoveryStakeholders: string[];   // Names of stakeholders (user-provided)

  // Four key capabilities (template requires 4)
  capability1: KeyCapability;
  capability2: KeyCapability;
  capability3: KeyCapability;        // Differentiator
  capability4: KeyCapability;        // Implementation edge

  // 3-Phase Framework
  phaseFramework: ThreePhaseFramework;

  // Full narrative sections (AI-generated from components)
  fullRecommendedSolution: string;
  fullPhaseDescription: string;
}

// =============================================================================
// SECTION 5: BUSINESS IMPACT & ROI
// =============================================================================

export interface ImpactTableRow {
  impactArea: string;                // KPI/Metric name (ICP or Cost Calculator)
  currentState: string;              // Baseline measurement (Cost Calculator)
  targetByDate: string;              // Target improvement + date (Cost Calculator)
  strategicValue: string;            // How it supports strategic goals (user-provided)
}

export interface BusinessImpactROI {
  // Vision statement
  visionFrom: string;                // Current pain state (user-provided)
  visionTo: string;                  // Future desired state (user-provided)

  // 3-row impact table (Executive KPI, Champion Metric, Committee Concern)
  executiveKPI: ImpactTableRow;      // Top-level business metric
  championMetric: ImpactTableRow;    // Champion's success metric
  committeeConcern: ImpactTableRow;  // Addresses committee objection

  // Organizational Benefits (4 key areas)
  financialROI: string;              // ROI calculation (Cost Calculator)
  operationalExcellence: string;     // Operational improvements (user-provided)
  competitiveAdvantage: string;      // Market positioning (user-provided)
  riskReduction: string;             // Risk mitigation (user-provided)

  // Full narrative (AI-generated from table)
  fullBenefitsNarrative: string;
}

// =============================================================================
// SECTION 6: INVESTMENT & IMPLEMENTATION
// =============================================================================

export interface TimelineMilestone {
  period: string;                    // "Month 1" or "Month 2-3" (user-provided)
  description: string;               // Milestone description (user-provided)
}

export interface InvestmentImplementation {
  // Investment
  totalInvestment: number;           // Dollar amount (user-provided)
  roiRatio: string;                  // "X:1 ratio" (Cost Calculator)
  roiTimeframe: string;              // "within 6 months" (Cost Calculator)

  // Timeline & Milestones (typically 3 phases)
  milestones: TimelineMilestone[];

  // Full narrative (AI-generated from components)
  fullInvestmentStatement: string;
  fullTimelineDescription: string;
}

// =============================================================================
// SECTION 7: STRATEGIC RATIONALE & NEXT STEPS
// =============================================================================

export interface ImmediateAction {
  actionNumber: number;              // 1, 2, 3
  actionType: string;                // "Committee Review", "Validation", "Approval"
  actionDescription: string;         // Full description (user-provided)
  targetDate?: string;               // Optional deadline (user-provided)
}

export interface StrategyNextSteps {
  // Why Now section (3 components)
  whyChangeNow: string;              // Business trigger (ICP or user-provided)
  whyYourCompany: string;            // Unique fit (user-provided)
  whyThisApproach: string;           // Methodology advantage (user-provided)

  // Values Alignment section (3 components)
  valueAlignment1: string;           // How solution aligns with company values (user-provided)
  valueAlignment2: string;
  valueAlignment3: string;

  // Champion Assessment (in champion's voice)
  championQuote: string;             // First-person assessment (user-provided or AI-assisted)
  alternativesConsidered: string[];  // List of alternatives evaluated (user-provided)
  uniqueDeliverable: string;         // What only you can deliver (user-provided)

  // Immediate Actions (typically 3 steps)
  immediateActions: ImmediateAction[];

  // Full narratives (AI-generated from components)
  fullChampionAssessment: string;
  fullNextStepsDescription: string;
}

// =============================================================================
// COMPLETE BUSINESS CASE DATA MODEL
// =============================================================================

export interface BusinessCaseData {
  // Unique identifier
  id: string;
  version: number;

  // All 7 sections
  header: BusinessCaseHeader;
  executiveSummary: ExecutiveSummary;
  businessChallenge: BusinessChallenge;
  approachDifferentiation: ApproachDifferentiation;
  businessImpactROI: BusinessImpactROI;
  investmentImplementation: InvestmentImplementation;
  strategyNextSteps: StrategyNextSteps;

  // Metadata for each field (tracking auto-population)
  fieldMetadata: Record<string, FieldMetadata>;

  // Source data references
  icpAnalysisId?: string;            // Reference to ICP Analysis
  costCalculatorId?: string;         // Reference to Cost Calculator results

  // Status
  status: 'draft' | 'review' | 'approved' | 'final';
  lastModified: Date;
  createdBy: string;

  // Export settings
  exportFormat: ExportFormat[];
  includeCharts: boolean;
  brandingSettings?: BrandingSettings;
}

// =============================================================================
// EXPORT & FORMATTING
// =============================================================================

export enum ExportFormat {
  PDF = 'PDF',
  DOCX = 'DOCX',
  HTML = 'HTML'
}

export interface BrandingSettings {
  companyLogo?: string;              // Base64 or URL
  primaryColor: string;              // Hex color
  secondaryColor: string;
  fontFamily: string;
  includeWatermark: boolean;
}

// =============================================================================
// AUTO-POPULATION CONFIGURATION
// =============================================================================

/**
 * Maps template fields to their auto-population sources
 */
export interface AutoPopulationConfig {
  // ICP Analysis → Business Case mappings
  icpMappings: {
    companyName: 'header.companyName';
    industryVertical: 'businessChallenge.affectedStakeholders';
    revenueRange: 'executiveSummary.businessChange';
    growthStage: 'executiveSummary.executiveGoal';
    // ... additional ICP field mappings
  };

  // Cost Calculator → Business Case mappings
  costCalculatorMappings: {
    totalCost: 'businessChallenge.dollarCost';
    roiRatio: 'investmentImplementation.roiRatio';
    roiTimeframe: 'investmentImplementation.roiTimeframe';
    currentRevenue: 'businessImpactROI.executiveKPI.currentState';
    targetRevenue: 'businessImpactROI.executiveKPI.targetByDate';
    // ... additional Cost Calculator field mappings
  };

  // AI Generation prompts for composite fields
  aiGenerationPrompts: {
    priorityHeadline: string;
    fullSummary: string;
    fullCostOfStatusQuo: string;
    fullRecommendedSolution: string;
    fullChampionAssessment: string;
    // ... additional AI generation prompts
  };
}

// =============================================================================
// VALIDATION & ERROR HANDLING
// =============================================================================

export interface ValidationError {
  field: string;
  section: keyof BusinessCaseData;
  message: string;
  severity: 'error' | 'warning' | 'info';
}

export interface ValidationResult {
  isValid: boolean;
  errors: ValidationError[];
  completionPercentage: number;      // 0-100
  missingRequiredFields: string[];
}

// =============================================================================
// TEMPLATE DEFAULTS
// =============================================================================

/**
 * Default values for new business case creation
 */
export const BUSINESS_CASE_DEFAULTS: Partial<BusinessCaseData> = {
  version: 1,
  status: 'draft',
  exportFormat: [ExportFormat.PDF],
  includeCharts: true,
  fieldMetadata: {},
  header: {
    priorityHeadline: '',
    championName: '',
    championTitle: '',
    partnerName: '',
    partnerCompany: '',
    generatedDate: new Date(),
    companyName: ''
  },
  executiveSummary: {
    businessChange: '',
    recommendedSolution: '',
    implementationTimeline: '',
    currentCostPain: '',
    strategicOutcome: '',
    executiveGoal: '',
    fullSummary: ''
  },
  businessChallenge: {
    currentRealityDescription: '',
    frequency: '',
    affectedCount: 0,
    affectedStakeholders: '',
    specificProblem: '',
    dollarCost: 0,
    consequenceTimeline: '',
    consequence: '',
    fullCostOfStatusQuo: ''
  },
  approachDifferentiation: {
    discoveryStakeholders: [],
    capability1: { title: '', problemSolved: '', businessOutcome: '' },
    capability2: { title: '', problemSolved: '', businessOutcome: '' },
    capability3: { title: '', problemSolved: '', businessOutcome: '' },
    capability4: { title: '', problemSolved: '', businessOutcome: '' },
    phaseFramework: { phase1: '', phase2: '', phase3: '' },
    fullRecommendedSolution: '',
    fullPhaseDescription: ''
  },
  businessImpactROI: {
    visionFrom: '',
    visionTo: '',
    executiveKPI: { impactArea: '', currentState: '', targetByDate: '', strategicValue: '' },
    championMetric: { impactArea: '', currentState: '', targetByDate: '', strategicValue: '' },
    committeeConcern: { impactArea: '', currentState: '', targetByDate: '', strategicValue: '' },
    financialROI: '',
    operationalExcellence: '',
    competitiveAdvantage: '',
    riskReduction: '',
    fullBenefitsNarrative: ''
  },
  investmentImplementation: {
    totalInvestment: 0,
    roiRatio: '',
    roiTimeframe: '',
    milestones: [],
    fullInvestmentStatement: '',
    fullTimelineDescription: ''
  },
  strategyNextSteps: {
    whyChangeNow: '',
    whyYourCompany: '',
    whyThisApproach: '',
    valueAlignment1: '',
    valueAlignment2: '',
    valueAlignment3: '',
    championQuote: '',
    alternativesConsidered: [],
    uniqueDeliverable: '',
    immediateActions: [],
    fullChampionAssessment: '',
    fullNextStepsDescription: ''
  }
};

// =============================================================================
// FIELD REQUIREMENTS
// =============================================================================

/**
 * Defines which fields are required for each business case status
 */
export const REQUIRED_FIELDS_BY_STATUS = {
  draft: [
    'header.companyName',
    'header.championName',
    'executiveSummary.businessChange',
    'businessChallenge.currentRealityDescription'
  ],
  review: [
    'header.companyName',
    'header.championName',
    'header.championTitle',
    'executiveSummary.businessChange',
    'executiveSummary.recommendedSolution',
    'businessChallenge.currentRealityDescription',
    'businessChallenge.dollarCost',
    'approachDifferentiation.capability1',
    'businessImpactROI.executiveKPI',
    'investmentImplementation.totalInvestment'
  ],
  approved: [
    // All fields required for approved status
    'header.*',
    'executiveSummary.*',
    'businessChallenge.*',
    'approachDifferentiation.*',
    'businessImpactROI.*',
    'investmentImplementation.*',
    'strategyNextSteps.*'
  ],
  final: [
    // All fields required + export settings
    'header.*',
    'executiveSummary.*',
    'businessChallenge.*',
    'approachDifferentiation.*',
    'businessImpactROI.*',
    'investmentImplementation.*',
    'strategyNextSteps.*',
    'exportFormat',
    'brandingSettings'
  ]
};
