#!/bin/bash
if [ $# -eq 0 ]; then
    echo "❌ Usage: npm run create:feature FeatureName"
    exit 1
fi

FEATURE=$1
FEATURE_DIR="src/features/${FEATURE}"

# Create feature structure
mkdir -p "${FEATURE_DIR}/components"
mkdir -p "${FEATURE_DIR}/types"
mkdir -p "${FEATURE_DIR}/hooks"
mkdir -p "${FEATURE_DIR}/services"
mkdir -p "${FEATURE_DIR}/utils"

# Generate main feature index
cat > "${FEATURE_DIR}/index.ts" << EOF
// ${FEATURE} Feature Exports
// Auto-generated by create-feature.sh

// Components
export * from './components';

// Types
export * from './types';

// Hooks
export * from './hooks';

// Services
export * from './services';

// Utils
export * from './utils';
EOF

# Generate components barrel export
cat > "${FEATURE_DIR}/components/index.ts" << EOF
// ${FEATURE} Components
// Export all components from this file

// Example:
// export { ${FEATURE}Dashboard } from './${FEATURE}Dashboard';
// export { ${FEATURE}Form } from './${FEATURE}Form';
EOF

# Generate types barrel export
FEATURE_LOWER=$(echo "${FEATURE}" | tr '[:upper:]' '[:lower:]')
cat > "${FEATURE_DIR}/types/index.ts" << EOF
// ${FEATURE} Types
// Export all types from this file

// Example:
// export type { ${FEATURE}Data } from './${FEATURE_LOWER}.types';
// export type { ${FEATURE}Props } from './${FEATURE_LOWER}.types';
EOF

# Generate hooks barrel export
cat > "${FEATURE_DIR}/hooks/index.ts" << EOF
// ${FEATURE} Hooks
// Export all hooks from this file

// Example:
// export { use${FEATURE}Data } from './use${FEATURE}Data';
// export { use${FEATURE}Actions } from './use${FEATURE}Actions';
EOF

# Generate services barrel export
cat > "${FEATURE_DIR}/services/index.ts" << EOF
// ${FEATURE} Services
// Export all services from this file

// Example:
// export { ${FEATURE_LOWER}Service } from './${FEATURE_LOWER}Service';
// export { ${FEATURE_LOWER}API } from './${FEATURE_LOWER}API';
EOF

# Generate utils barrel export
cat > "${FEATURE_DIR}/utils/index.ts" << EOF
// ${FEATURE} Utils
// Export all utilities from this file

// Example:
// export { format${FEATURE}Data } from './format${FEATURE}Data';
// export { validate${FEATURE}Input } from './validate${FEATURE}Input';
EOF

echo "✅ Created feature structure for ${FEATURE}"
echo "📁 Created directories:"
echo "   - ${FEATURE_DIR}/components"
echo "   - ${FEATURE_DIR}/types"
echo "   - ${FEATURE_DIR}/hooks"
echo "   - ${FEATURE_DIR}/services"
echo "   - ${FEATURE_DIR}/utils"
echo "⚠️  Remember to:"
echo "   1. Use 'npm run create:component ${FEATURE} ComponentName' to add components"
echo "   2. Export new components/types/hooks from barrel files"
echo "   3. Follow TypeScript strict mode (no any types)"